os:
  - linux

language: node_js

script:
  - npm run lint
  - npm run test
# - npm audit

node_js:
  - '12'
  - '10'

dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
