// flow-typed signature: 4871606049cee4b454777c0a3350ebcd
// flow-typed version: <<STUB>>/animated-scroll-to_v^1.2.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animated-scroll-to'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animated-scroll-to' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'animated-scroll-to/animated-scroll-to' {
  declare module.exports: any;
}

// Filename aliases
declare module 'animated-scroll-to/animated-scroll-to.js' {
  declare module.exports: $Exports<'animated-scroll-to/animated-scroll-to'>;
}
