// flow-typed signature: 1fbe67b58c3c3e034d206ef47cea1a8f
// flow-typed version: <<STUB>>/jest-alias-module-loader_v^1.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-alias-module-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-alias-module-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-alias-module-loader/JestAliasModuleLoader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-alias-module-loader/JestAliasModuleLoader.js' {
  declare module.exports: $Exports<'jest-alias-module-loader/JestAliasModuleLoader'>;
}
