// flow-typed signature: e0ee57461ceb66895b0074fec2f55028
// flow-typed version: <<STUB>>/plovr_v^7.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plovr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plovr' {
  declare module.exports: any;
}
