// flow-typed signature: ddcef1b4637d21954190ce44aa244a26
// flow-typed version: <<STUB>>/webpack-command_v^0.4.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-command'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-command' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-command/lib/cli' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/commands/Command' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/commands/HelpCommand' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/commands/index' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/commands/TeachCommand' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/compiler' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/config' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/entry' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/flags/advanced' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/flags/config' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/flags/general' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/flags/index' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/flags/module' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/flags/optimization' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/flags/output' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/flags/resolver' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/flags/util' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/global' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/progress' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/reporters/BasicReporter' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/reporters/JsonReporter' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/reporters/parse' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/reporters/Reporter' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/reporters/stylish/style' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/reporters/StylishReporter' {
  declare module.exports: any;
}

declare module 'webpack-command/lib/WebpackCommandError' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-command/lib/cli.js' {
  declare module.exports: $Exports<'webpack-command/lib/cli'>;
}
declare module 'webpack-command/lib/commands/Command.js' {
  declare module.exports: $Exports<'webpack-command/lib/commands/Command'>;
}
declare module 'webpack-command/lib/commands/HelpCommand.js' {
  declare module.exports: $Exports<'webpack-command/lib/commands/HelpCommand'>;
}
declare module 'webpack-command/lib/commands/index.js' {
  declare module.exports: $Exports<'webpack-command/lib/commands/index'>;
}
declare module 'webpack-command/lib/commands/TeachCommand.js' {
  declare module.exports: $Exports<'webpack-command/lib/commands/TeachCommand'>;
}
declare module 'webpack-command/lib/compiler.js' {
  declare module.exports: $Exports<'webpack-command/lib/compiler'>;
}
declare module 'webpack-command/lib/config.js' {
  declare module.exports: $Exports<'webpack-command/lib/config'>;
}
declare module 'webpack-command/lib/entry.js' {
  declare module.exports: $Exports<'webpack-command/lib/entry'>;
}
declare module 'webpack-command/lib/flags/advanced.js' {
  declare module.exports: $Exports<'webpack-command/lib/flags/advanced'>;
}
declare module 'webpack-command/lib/flags/config.js' {
  declare module.exports: $Exports<'webpack-command/lib/flags/config'>;
}
declare module 'webpack-command/lib/flags/general.js' {
  declare module.exports: $Exports<'webpack-command/lib/flags/general'>;
}
declare module 'webpack-command/lib/flags/index.js' {
  declare module.exports: $Exports<'webpack-command/lib/flags/index'>;
}
declare module 'webpack-command/lib/flags/module.js' {
  declare module.exports: $Exports<'webpack-command/lib/flags/module'>;
}
declare module 'webpack-command/lib/flags/optimization.js' {
  declare module.exports: $Exports<'webpack-command/lib/flags/optimization'>;
}
declare module 'webpack-command/lib/flags/output.js' {
  declare module.exports: $Exports<'webpack-command/lib/flags/output'>;
}
declare module 'webpack-command/lib/flags/resolver.js' {
  declare module.exports: $Exports<'webpack-command/lib/flags/resolver'>;
}
declare module 'webpack-command/lib/flags/util.js' {
  declare module.exports: $Exports<'webpack-command/lib/flags/util'>;
}
declare module 'webpack-command/lib/global.js' {
  declare module.exports: $Exports<'webpack-command/lib/global'>;
}
declare module 'webpack-command/lib/index.js' {
  declare module.exports: $Exports<'webpack-command/lib/index'>;
}
declare module 'webpack-command/lib/progress.js' {
  declare module.exports: $Exports<'webpack-command/lib/progress'>;
}
declare module 'webpack-command/lib/reporters/BasicReporter.js' {
  declare module.exports: $Exports<'webpack-command/lib/reporters/BasicReporter'>;
}
declare module 'webpack-command/lib/reporters/JsonReporter.js' {
  declare module.exports: $Exports<'webpack-command/lib/reporters/JsonReporter'>;
}
declare module 'webpack-command/lib/reporters/parse.js' {
  declare module.exports: $Exports<'webpack-command/lib/reporters/parse'>;
}
declare module 'webpack-command/lib/reporters/Reporter.js' {
  declare module.exports: $Exports<'webpack-command/lib/reporters/Reporter'>;
}
declare module 'webpack-command/lib/reporters/stylish/style.js' {
  declare module.exports: $Exports<'webpack-command/lib/reporters/stylish/style'>;
}
declare module 'webpack-command/lib/reporters/StylishReporter.js' {
  declare module.exports: $Exports<'webpack-command/lib/reporters/StylishReporter'>;
}
declare module 'webpack-command/lib/WebpackCommandError.js' {
  declare module.exports: $Exports<'webpack-command/lib/WebpackCommandError'>;
}
